version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myAudioHostingDb
    depends_on:
      - mongo
    restart: always

  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db

volumes:
  mongo_data: